name: Build & publish module to Tiny Systems repository

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: |
          echo "Preparing a release"
          echo "Module name ${{ github.event.repository.name }}"
          go run cmd/main.go build -v ${{github.ref_name}} -n ${{ github.event.repository.name }} -d ${{secrets.TINY_DEV_SECRET}} -c nats://nats.tinysystems.io:4222
