name: releaser

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: release
        id: release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
